### ISSUE TITLE
Format all device properties

### ISSUE THREAD

**Issue by vanbalken** [vanbalken/arris-tg2492lg#3]
Not all the properties that are received for the connected devices are mapped/formatted correctly:

- [x] ipv6 isn't formatted
- [x] `online` should be a boolean instead of a string
- [ ] `type` is only a id and should be mapped to an understandable value

**Comment by vanbalken** [comment]
Fixed `online` and an empty yeardate in https://github.com/vanbalken/arris-tg2492lg/pull/4

**Comment by gert-willem** [comment]
I do not write englisch very well. 
can you tell me how i can replace the upc connect into your program.
i hope that i can see again every connected wifi user
i 'm new in home assistant but everysthing is in englisch so very difficult to read.

**Comment by vanbalken** [comment]
Hello Gert-Willem,

UPC Connect is a integration in Home Assistant that works for one of the two types of Ziggo Connectbox routers. It uses a library like this one to work.

For the other Ziggo Connectbox to work, the one this library works for, someone needs to create a new integration in Home Assistant. This hasn't been done yet.

I've submitted a feature request [Add presence detection for the Arris TG2492LG router (aka Ziggo Connectbox)](https://community.home-assistant.io/t/add-presence-detection-for-the-arris-tg2492lg-router-aka-ziggo-connectbox/147205) but it hasn't received any votes yet or any comments.


In Dutch:

_Hoi Gert-Willem,_

_Ik vermoed dat Nederlands je beter af gaat ;) De Connectbox van Ziggo zijn eigenlijk twee verschillende routers. De UPC Connect integratie in Home Assistant werkt voor één van deze routers. Hiervoor wordt gebruik gemaakt van een project/programma zoals deze. Dit programma werkt voor de andere router._

_Om dit programma te gebruiken in Home Assistant zal een nieuwe integratie geschreven moeten worden voor Home Assistant. Dit is programmeerwerk en is nog niet gedaan._ 

_Ik heb zelf geen ervaring met het ontwikkelen voor Home Assistant en heb daar de komende tijd ook geen tijd voor. Ik heb hiervoor een feature request ingediend: [Add presence detection for the Arris TG2492LG router (aka Ziggo Connectbox)](https://community.home-assistant.io/t/add-presence-detection-for-the-arris-tg2492lg-router-aka-ziggo-connectbox/147205) Alleen heb ik daar geen reactie op gekregen._

**Comment by gert-willem** [comment]
Dank je.
Ik dacht dat je het zover uitgewerkt had dat de basis kon werken.
Vandaag is de tc7200 die wel werkte vervangen door de tg2492lg en nu moet
ik iets anders bedenken voor aanwezigheid detectie.
Bedankt voor je antwoord iig.

Gert-Willem

Ski en snowboardschool Holland Indoor Sport
skiën snowboarden klimmen survival boogschieten zeskampspellen bouwen met
bamboe
￼
Einsteinweg 6 (ingang sportcentrum Halfweg)
3208LA Spijkenisse
Gert-Willem: 06-41056405
E-mail: info@hollandindoorsport.nl
Site: hollandindoorsport.nl
Bank Rekening : NL17KNAB0723548110
tnv Ski en snowboardschool holland indoor ski
Beoordeel ons bedrijf op Allebedrijvenin en bekijk de waardering van onze
klanten.
De langste afdaling dicht bij huis.
Ook voor huur, slijpen, waxen en afstellen van uw wintersportmateriaal


Op do 14 nov. 2019 21:03 schreef Arjan van Balken <notifications@github.com

**Comment by vanbalken** [comment]
Created #9 for missing formatted device property.
