### ISSUE TITLE
async_login aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found'

### ISSUE THREAD

**Issue by pgmgb** [vanbalken/arris-tg2492lg#31]
I was looking for a way to accessing my Sunrise Connect Box 2 (I'm from Switzerland :-)) to get a list of the connected devices. This way, I found your Python module on Pip and tried it. Unfortunately, I receive the following error message with your examples:

```bash
Traceback (most recent call last):
  File "/home/pi/Desktop/test.py", line 20, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/pi/Desktop/test.py", line 11, in main
    devices = await connect_box.async_get_connected_devices()
  File "/home/pi/.local/lib/python3.9/site-packages/arris_tg2492lg/connect_box.py", line 71, in async_get_connected_devices
    credential = await self._async_get_credential()
  File "/home/pi/.local/lib/python3.9/site-packages/arris_tg2492lg/connect_box.py", line 108, in _async_get_credential
    await self.async_login()
  File "/home/pi/.local/lib/python3.9/site-packages/arris_tg2492lg/connect_box.py", line 43, in async_login
    response.raise_for_status()
  File "/home/pi/.local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('http://192.168.0.1/login?arg=XXX&_n=XXX')
```

Seems like, that the device does not provide the endpoint `/login` or do I miss something?

Sunrise Connect Box 2 details:
```
"family":"852",
"modelname":"TG2492LG-85"
```

Thank you,
Patrick

**Comment by vanbalken** [comment]
Hi! 

I always find it nice to here that people use/try my code! Thx! 

Due to personal circumstances I don't have time to really look into your issue.

I'd suggest logging in using the browser while looking at the network tab in the developer toolbar. A similar login request should happen. Maybe that can help you.

**Comment by pgmgb** [comment]
Thank you for the quick response.
Seems, that there is no call against `http://192.168.0.1/login` anymore.
I need to take a deeper look into it.

**Comment by mjaspers2mtu** [comment]
Same problem here, my router uses http://192.168.178.1/php/ajaxSet_Password.php when logging in, but sadly my knowledge is not enough to understand how to go any further ;/

**Comment by vanbalken** [comment]
Hi @mjaspers2mtu,

Based on the provided URL it appears your router runs different software than the one I developed this library against. I'm afraid I will be unable to help you. Can you provide model number and maybe your provider? That can help with better understanding when this library works or not
